import type { MembershipFormContent } from '@/types/content';

export const membershipFormContent: MembershipFormContent = {
  eyebrow: 'Asociate',
  title: 'Solicitud de socio',
  description:
    'Completá tus datos para solicitar el ingreso como socio del Centro. La Comisión Directiva se pondrá en contacto para continuar con el trámite (categoría de socio, número de asociado y firma).',
  sections: {
    personal: 'Datos personales',
    address: 'Domicilio',
    referrer: 'Socio que presenta (opcional)',
  },
  steps: {
    personal: 'Datos personales',
    address: 'Domicilio',
    nationality: 'Nacionalidad',
    confirmation: 'Confirmación',
  },
  fields: {
    firstName: 'Nombres',
    lastName: 'Apellidos',
    documentType: 'Tipo de documento',
    documentNumber: 'Número de documento',
    birthDate: 'Fecha de nacimiento',
    birthCountry: 'País de nacimiento',
    birthProvince: 'Provincia',
    birthConcello: 'Concello / Municipio',
    birthLocality: 'Localidad',
    galicianOrigin: '¿Es nativo, hijo o nieto de gallego?',
    spanishRegistration: 'Empadronamiento en España',
    maritalStatus: 'Estado civil',
    spouseName: 'Cónyuge',
    children: 'Hijos',
    profession: 'Profesión',
    street: 'Calle',
    streetNumber: 'Número',
    floor: 'Piso',
    apartment: 'Depto.',
    locality: 'Localidad',
    postalCode: 'Código postal',
    phone: 'Teléfono',
    mobilePhone: 'Teléfono móvil',
    email: 'Mail',
    referrerName: 'Nombre y apellido',
    referrerMemberNumber: 'Socio N°',
    photo: 'Foto',
  },
  photoHint:
    'Se toma en el momento con la cámara del celular o la webcam (no se puede subir una foto ya existente). Además de quedar en tu legajo, se usa para verificar tu identidad y sustituye a la firma en esta solicitud.',
  photoCameraLabel: 'Usar cámara',
  photoCaptureLabel: 'Capturar',
  photoRetakeLabel: 'Volver a tomar',
  photoRequiredMessage: 'Sacate una foto con la cámara para poder enviar la solicitud.',
  photoCameraErrorMessage:
    'No pudimos acceder a la cámara. Revisá los permisos del navegador e intentá de nuevo.',
  documentTypeOptions: ['DNI', 'LC', 'LE', 'CI', 'Pasaporte'],
  maritalStatusOptions: ['Soltero/a', 'Casado/a', 'Divorciado/a', 'Viudo/a'],
  galicianOriginOptions: ['Nativo', 'Hijo', 'Nieto', 'No aplica'],
  declaration:
    'Declaro y acepto los Estatutos vigentes y los reglamentos de la Institución.',
  submitLabel: 'Enviar solicitud',
  submitLoadingLabel: 'Enviando...',
  successMessage:
    '¡Gracias! Recibimos tu solicitud. La Comisión Directiva se comunicará para continuar con el trámite.',
  errorMessage: 'Hubo un error al enviar tu solicitud. Intentá nuevamente.',
  confirmEmailSentMessage:
    'Te enviamos un mail para confirmar tu identidad: hacé clic en el link cuando lo recibas. Mientras tanto, o si preferís, también podés confirmar por WhatsApp.',
  confirmWhatsappLabel: 'Confirmar por WhatsApp',
  confirmWhatsappMessageTemplate: 'Confirmo mi solicitud de asociación — código: {code}',
};
